module.exports = {
    name: 'traditions',
    description: 'this is traditions command',
    execute(message,args){
        message.channel.send(':sparkles::christmas_tree::confetti_ball: **TOP 10 CHRISTMAS TRADITIONS (IN THE U.S)** :sparkles::christmas_tree::confetti_ball:');
        message.channel.send('**1. Watch a Christmas Movie**\n'+
        'One uniquely American tradition during the holidays is watching specific movies and TV shows that put us in the holiday spirit. There are a number of favorites that range from old movies to cartoons. What better way to celebrate the holidays than with timeless classics such as “It’s A Wonderful Life,” “Miracle on 34th St.”, or “The Christmas Story?” Don’t forget those cartoons that will forever be a part of the holidays, such as “Rudolf the Red-Nosed Reindeer,” “A Charlie Brown Christmas,” and “Frosty The Snowman.” While some of those older movies and cartoons may not be as popular for the younger generation, you can always find more recent family favorites that bring a smile to your face, such as “Home Alone,” “Elf,” “ or “The Grinch Who Stole Christmas.”\nIf you send -movies, you can find good movies ideas!');
        message.channel.send('https://cdn3.minted.com/files/content/minted_landing_banners/Christmas_Traditions_lp_image_1.png');
        message.channel.send('**2. Set up a Christmas Tree**\n'+
        'Once you have had your fill of binge-watching holiday movies, you may want to participate in one of the oldest Christmas traditions, which dates back to the 15th century. That is, of course, selecting and decorating a Christmas tree. Each year, 30-35 million real Christmas trees are sold in the United States alone. Whether you go and cut down your own tree, buy one, or use an artificial tree, decorating a tree is one of the first signs that the Christmas holiday season is upon us.\nIf you do plan to venture out and find a real tree, finding the perfect one may take some time. You may want to consider things such as the scent, how sturdy the branches are in order to hold all of the ornaments, whether it drops a lot of needles, the price, color, shape, height, and so on. While there are a lot of variables to consider, you will know when you find the perfect one for your home.');
        message.channel.send('https://cdn3.minted.com/files/content/minted_landing_banners/Christmas_Traditions_lp_image_2.png');
        message.channel.send('**3. String home and yard decorations**\n'+
        'Holiday decorating is not limited to just the tree. Decorate your home with Christmas light displays and be the envy of your neighborhood. Some displays even coordinate the lights to turn off and on in unison with popular Christmas songs. Families often travel from miles around to search for the most beautiful light displays.\nWhile you are decorating your home, don’t forget to hang stockings for each of your family members, even that special pet. Remember, you don’t have to have a fireplace to hang stockings. You can hang them from the staircase railing, from garland, on a bookcase, the footboard or headboard of your bed, your TV stand, and so many other places. Be creative! You may also want to read through our post on Christmas mantle decoration ideas.');
        message.channel.send('https://cdn3.minted.com/files/content/minted_landing_banners/2020_christmas_traditions_image_number_4.jpg');
        message.channel.send('**4. Hang the mistletoe**\n'+
        'The tradition of hanging a strand of mistletoe in the house goes back to the 2nd or 3rd century. Mistletoe was said to have powers that bring good luck to a home by getting rid of evil spirits. More commonly, it was also used as a sign of love and friendship. This is where the custom of kissing under the Mistletoe originates. If you’re curious about where you can purchase mistletoe nearby, consider Home Depot, Lowes, your local hardware store, the garden section of Walmart or Kmart, or the pop-up Christmas tree sales tent.');
        message.channel.send('https://cdn3.minted.com/files/content/minted_landing_banners/2020_christmas_traditions_lp_image_2.jpg');
        message.channel.send('**5. Host or join a christmas dinner**\n'+
        'Of the many Christmas traditions celebrated around the world, the most common thread is the celebration of a shared meal. Create memories and reflect on the year by joining friends and family together to enjoy a delicious meal. If the idea of interacting with a larger group this holiday season has you feeling uneasy, look to just host a special meal with your immediate household.\nAs you might imagine, there are countless food choices that people enjoy throughout the world during Christmas, however, there are some main staples that are a part of many Christmas meals. Some classics include roast turkey, ham or chicken, potatoes, stuffing, and of course you cannot forget the gravy.');
        message.channel.send('https://media.timeout.com/images/105839283/image.jpg');
        message.channel.send('**6. Bake christmas cookies and decorate gingerbread houses**\n'+
        'While we all love a good meal, the actual process of baking together is often a family tradition in itself. Making cookies, baking pies, or building gingerbread houses falls in line with the holiday spirit that it is better to give than receive. Don’t forget to set a few cookies aside (with a glass of milk) for when Santa pays a visit. Some popular Christmas snacks include:\n-Sugar cookies with intricate decorations\n-Gingerbread men\n-Yule log\n-Pumpkin Pie\n-Puppy chow/reindeer chow (Chex Mix treat)');
        message.channel.send('https://cdn3.minted.com/files/content/minted_landing_banners/Christmas_Traditions_lp_image_3.png');
        message.channel.send('**7. Exchange gifts**\n'+
        'Gift giving is one of the most beloved traditions of Christmas (especially for children) and it goes back to when the Three Wise Men offered gifts of gold, frankincense, and myrrh to baby Jesus in the manger. Gifts are usually placed under the Christmas tree or within stockings, but the timing and place could vary depending on where you live in the world. For example, in some European countries (Netherlands, Germany, Czechia), some presents are opened as early as December 5th, right before St. Nicholas’ Day on December 6th. In America, we have created a few unique ways to exchange gifts in large group settings, such as Secret Santa, White Elephant and Christmas Story Pass-Around\nThe tradition of giving gifts to others is centered around showing how much we appreciate others and value the role they play in our lives. As you go about your holiday shopping, remember Christmas is a time to think about others and the joy of giving rather than receiving. Need some help finding the perfect personalized gift for your friends and family this year? Browse Minted’s Holiday Gift Guide for our top picks this 2021 season.');
        message.channel.send('https://cdn3.minted.com/files/mintedProductsImages/MIN/NWR/ZKZ/MIN-ZKZ-NWR-001_A_PZ.jpg');
        message.channel.send('**8. Send christmas cards**\n'+
        'Exchanging greeting cards has become a huge tradition during the holidays. It is a great way to communicate with friends and family and express that you are thinking of them. This year has been a very unusual one, with many of us not venturing too far from home, which means it has likely been a while since some of your more distant friends and family have seen your face. The annual holiday card greeting will be appreciated that much more this December. Did you know that in the United States alone, more than two billion Christmas cards are sent annually?');
        message.channel.send('https://parade.com/wp-content/uploads/2021/11/Christmas-Card-Etiquette-Feat.jpg');
        message.channel.send('**9. Hide an elf on the shelf**\n'+
        'The Elf on a Shelf phenomenon became a family Christmas tradition close to 15 years ago. It is derived from a children’s story about Santa’s elves watching over children and reporting back to Santa about the good and bad activities of the children observed that day.\nThe tradition has become extremely popular amongst adults and kids, as the Elf hides in a new spot every morning around the house and the kids try to find it. The elves are said to have magical powers derived from being adopted and loved by a child. However, the kids must follow one simple rule and that is to not touch the elf or the elves may lose their magic. If touched, the elves cannot report the children’s Christmas wishes back to Santa.');
        message.channel.send('https://cdn3.minted.com/files/content/minted_landing_banners/Christmas_Traditions_lp_image_4.png');
        message.channel.send('**10. Listen to christmas songs and go caroling**\n'+
        'Music plays a large role in many Christmas traditions around the world. We listen to holiday favorites with family and friends and have our playlist of favorite songs, such as “O Holy Night,” “Let It Snow,” “Jingle Bells,” and many others.\nIf you send -songs, you can find good song ideas!');
        message.channel.send('https://hips.hearstapps.com/clv.h-cdn.co/assets/15/47/1448036654-gettyimages-121808841.jpg');
        message.channel.send('*source: https://www.minted.com/lp/christmas-traditions*');

    }
}